export type Theme = "light" | "dark" | "system";
export type IconSize = "small" | "medium" | "large";
export type ItemBackground = "transparent" | "subtle" | "visible";
export type SelectedItemBackground = "white" | "black";
export type FullscreenDetectionMode = "fullscreenOnly" | "fullscreenAndMaximized";

export interface Settings {
	theme: Theme;
	accentColor: string;
	gridEnabled: boolean;
	gridWidth: number;
	gridHeight: number;
	gridGapX: number;
	gridGapY: number;
	iconSize: IconSize;
	cornerRadius: number;
	backgroundBlur: boolean;
	wallpaperCompatible: boolean;
	itemBackground: ItemBackground;
	selectedItemBackground: SelectedItemBackground;
	selectedItemBlur: boolean;
	globalBlur: boolean;
	fontSize: number;
	hideShortcutBadge?: boolean;
	hideFileExtensions?: boolean;
	iconOpacity?: number;
	textOpacity?: number;
	iconGlow?: boolean;
	iconGlowRadius?: number;
	iconGlowIntensity?: number;
	doubleClickHide?: boolean;
	autoStart?: boolean;
	autoStartHighPriority?: boolean;
	parallaxEnabled?: boolean;
	parallaxIntensity?: number;
	showGridOnDrag?: boolean;
	language?: "zh" | "en";
	performanceModeEnabled?: boolean;
	fullscreenDetectionMode?: FullscreenDetectionMode;
	customWidgets?: any[];
}
